version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    command: /bin/sh -c "apk update && apk add nano && nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  attacker:
    container_name: attacker
    image: ubuntu:22.04
    command: sh -c "apt update && apt-get install siege && tail -f /dev/null"
